name: Run go-tuf-mirror
on:
  workflow_run:
    workflows: ["TUF-on-CI publish"]
    types:
      - completed
    branches:
      - publish
  workflow_dispatch:
env:
  DOCKER_CONFIG: ${{ github.workspace }}/.docker
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dockerpublicbot
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}
      - name: Mirror metadata
        uses: docker/go-tuf-mirror/actions/metadata@c6bd5df346167fce36234d5eb651e74e89382e48 # v0.1.9
        with:
          source: https://docker.github.io/tuf/metadata
          destination: docker://docker/tuf-metadata:latest
          tuf-root: prod
          flags: "-f"
      - name: Mirror targets
        uses: docker/go-tuf-mirror/actions/targets@c6bd5df346167fce36234d5eb651e74e89382e48 # v0.1.9
        with:
          metadata: https://docker.github.io/tuf/metadata
          source: https://docker.github.io/tuf/targets
          destination: docker://docker/tuf-targets
          tuf-root: prod
          flags: "-f"
