name: Run go-tuf-mirror
on:
  workflow_run:
    workflows: ["TUF-on-CI publish"]
    types:
      - completed
    branches:
      - publish
  workflow_dispatch:
env:
  DOCKER_CONFIG: ${{ github.workspace }}/.docker
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dockerpublicbot
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}
      - name: Mirror metadata
        uses: docker/go-tuf-mirror/actions/metadata@7e98aaf32ebccc7415882c0365908ed86cdeaf9e # v0.2.0
        with:
          targets: https://docker.github.io/tuf/targets
          source: https://docker.github.io/tuf/metadata
          destination: docker://docker/tuf-metadata:latest
          tuf-root: prod
          flags: "-f"
      - name: Mirror targets
        uses: docker/go-tuf-mirror/actions/targets@7e98aaf32ebccc7415882c0365908ed86cdeaf9e # v0.2.0
        with:
          metadata: https://docker.github.io/tuf/metadata
          source: https://docker.github.io/tuf/targets
          destination: docker://docker/tuf-targets
          tuf-root: prod
          flags: "-f"
