name: TUF-on-CI repository tests

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "17 4,10,16,22 * * *"

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checking out the repository
    steps:
      - name: Smoke test TUF-on-CI repository with a TUF client
        uses: theupdateframework/tuf-on-ci/actions/test-repository@95dc66aba6102bbe911ef93c69395ff62ed69bd4 # v0.11.0

  update-issue:
    runs-on: ubuntu-latest
    needs: [smoke-test]
    # During workflow_call, caller updates issue
    if: always() && !cancelled() && github.workflow == 'TUF-on-CI repository tests'
    permissions:
      issues: write # for modifying Issues
      contents: read # for checking out the repository
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Update the issue for the workflow
        uses: theupdateframework/tuf-on-ci/actions/update-issue@95dc66aba6102bbe911ef93c69395ff62ed69bd4 # v0.11.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          success: ${{ !contains(needs.*.result, 'failure') }}
